### ISSUE TITLE
socket connection reset by peer

### ISSUE THREAD

**Issue by RavenKyu** [RavenKyu/restful-modbus-api#9]
* when socket disconnected, failing next connection

**Comment by RavenKyu** [comment]
```bash
** Error:  [Input/Output] [Errno 54] Connection reset by peer
2020-11-26 21:42:35,411 |   ERROR | apscheduler.executors.default | Job "Collector.request_data (trigger: interval[0:00:03], next run at: 2020-11-26 21:42:38 KST)" raised an exception | /Users/limdukkyu/Works/projects/modbus-restapi/venv/lib/python3.8/site-packages/apscheduler/executors/base.py:131
Traceback (most recent call last):
  File "/Users/limdukkyu/Works/projects/modbus-restapi/venv/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/limdukkyu/Works/projects/modbus-restapi/restful_modbus_api/manager.py", line 124, in request_data
    data = module._main()
  File "<string>", line 65, in _main
  File "<string>", line 20, in main
TypeError: object of type 'NoneType' has no len()

```
